name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '6,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3

    - name: Fetch latest data
      run: |-
        curl 'https://www.fire.ca.gov/api/sitecore/Incident/GetFiresForMap' \
          -X POST --data-raw 'showFeatured=False' | jq > incidents-june-2023-format.json

    - name: Set up Git user
      run: |-
        git config --global user.name "Automated"
        git config --global user.email "actions@users.noreply.github.com"

    - name: Commit and push if it changed
      run: |-
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push https://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@github.com/amirguterman/ws.git
