name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '6,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        branch: main
        force: true
    - name: Fetch latest data
      run: |-
        curl 'https://www.fire.ca.gov/api/sitecore/Incident/GetFiresForMap' \
          -X POST --data-raw 'showFeatured=False' | jq > incidents-june-2023-format.json

    - name: Set up Git user
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        branch: main
        force: true
      run: |-
        git config --global user.name "Amir Guterman"
        git config --global user.email "amirguterman@gmail.com"

    - name: Commit and push if it changed
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        branch: main
        force: true
      run: |-
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
